sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t mmgtools/mmg-dev .

script:
  - |
    docker run -v $PWD:/root/src --name mmg-dev mmgtools/mmg-dev bash -c \
      "mkdir -p $HOME/src/build && \
       cd build && \
       cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_TESTING=ON .. && \
       make && \
       ctest"
